// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerShop.Data;

#nullable disable

namespace SneakerShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SneakerShop.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SneakerShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic 90s comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "Air Max Retro",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "High performance knit.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Boost Runner",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Minimalist leather sneaker.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "Court Classic",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Everyday streetwear staple.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600",
                            Name = "Dunk Low Panda",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Primeknit comfort and style.",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600",
                            Name = "Yeezy 350 V2",
                            Price = 230.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "The one that started it all.",
                            ImageUrl = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600",
                            Name = "Jordan 1 High",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Retro hoops silhouette.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "NB 550 Vintage",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Maximum energy return.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Ultraboost 1.0",
                            Price = 190.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Chunky retro-future design.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "RS-X Toys",
                            Price = 115.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Split tongue classic.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600",
                            Name = "Gel-Lyte III",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Clean tennis aesthetics.",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600",
                            Name = "Club C 85",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Upgraded canvas icon.",
                            ImageUrl = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600",
                            Name = "Chuck 70 High",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Skate ready durability.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "Old Skool Pro",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Crisp white leather.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Air Force 1 '07",
                            Price = 115.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Off-road performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "XT-6 Trail",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Water ripple inspired.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600",
                            Name = "Air Max 97",
                            Price = 175.00m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Indoor soccer legend.",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600",
                            Name = "Samba OG",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Y2K running style.",
                            ImageUrl = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600",
                            Name = "NB 2002R",
                            Price = 140.00m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Vintage hoops design.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "Blazer Mid '77",
                            Price = 105.00m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Flight club essential.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Jordan 4 Retro",
                            Price = 210.00m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Suede perfection.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "Gazelle Indoor",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 22,
                            Description = "B-boy certified.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600",
                            Name = "Suede Classic",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Ankle support for days.",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600",
                            Name = "Sk8-Hi",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Tech runner revival.",
                            ImageUrl = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600",
                            Name = "Kayano 14",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Plush daily trainer.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "Clifton 9",
                            Price = 145.00m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Maximum cushioning.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Cloudmonster",
                            Price = 170.00m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Breathable mesh overlay.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "Vomero 5",
                            Price = 160.00m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Elephant print details.",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600",
                            Name = "Jordan 3 Retro",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Strap it down.",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600",
                            Name = "Forum Low",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Made in USA excellence.",
                            ImageUrl = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600",
                            Name = "NB 990v6",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Chunky platform style.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                            Name = "Run Star Hike",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Timeless everyday wear.",
                            ImageUrl = "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600",
                            Name = "Classic Leather",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Smooth transition running.",
                            ImageUrl = "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600",
                            Name = "Wave Rider 27",
                            Price = 140.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SneakerShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SneakerShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SneakerShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SneakerShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
